plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven {
		name = 'Fabric'
		url = 'https://maven.fabricmc.net/'
	}
}

loom {
	mods {
		"${project.mod_id}" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	inputs.property 'version', project.version
	inputs.property 'mod_id', project.mod_id
	inputs.property 'mod_name', project.mod_name
	inputs.property 'loader_version', project.loader_version
	inputs.property 'minecraft_version', project.minecraft_version

	filesMatching('fabric.mod.json') {
		expand(
			version: project.version,
			mod_id: project.mod_id,
			mod_name: project.mod_name,
			loader_version: project.loader_version,
			minecraft_version: project.minecraft_version
		)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		create('mavenJava', MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
